; Example configuration for 3DEngineTest
[Video]
fullscreen = false
; renderer can be: direct3d (synonyms: dx12/d3d12/d3d/directx), vulkan (vulcan/vk), methane (methanekit/methane-kit/mk)
renderer = methane
width = 800
height = 600

[Logging]
; Maximum size of active log file before rotation (in megabytes)
maxFileSizeMB = 1
; Maximum number of rotated log files to keep
maxFileCount = 3

[Engine]
; Root directories for engine assets
dirModels = "assets/models"
dirTextures = "assets/maps"
dirSounds = "assets/sounds"
dirScenes = "assets/scenes"
StartupScene = "example_scene.glb"

[Methane]
; MethaneKit specific options

[Direct3d]
; Direct3D specific options